### ISSUE TITLE
Recursive directory taring

### ISSUE THREAD

**Issue by juliangaal** [kennyparsons/tarnation#2]
Hi!

> Future versions will accept a directory and a flag that will recursively handle all sub-directories as if they were individually backed up

`tar -cvzf mytarfile.tgz mydir/` will backup each individual subdirectory as well! 
* `-c` create
* `-v` verbose
* `-z` pass through gzip
* `-f` file

I'm not sure how you to your original statement about tar. Cheers

**Comment by kennyparsons** [comment]
Tarnation does back up all subdirectories. But sub directories do not have their own versions separate from the parent directories. So for example, I back up foldera which has 2 sub folders, subfolder1, and subfolder2. If I want to restore just one of the sub folders, I have to restore the entire backup of foldera. Not the best solution for working directories but I use it as a disaster recovery option. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
